language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: JW9CAn8PoYT/o/6eRGmi4yHbJByk7z/GZhEFv1OVf+Is6DNTz0JAaS8kYA1OYrxyS/GaTty+ysOGECq0u05XKQGhzB8f32jZmdRSYPBccMrQH8trbtqCfFVBvXYQ1dHnpjxeMyt7TmC+ig9UpTYKpEBAXr1/ttAkKNJlpGu4DYAxhgH2YOP6/2a1yObHGdFvpfAx7NdPZ/xWVSqTYl0gJ+/+ibrs47qze3yD/AgABQHlG28GVBpVsnYhtDMlpPWD9uCDcJiUg+CiR0Gp+Oe02PQ75N3neYBnV3rnZpPXQQ7iYU/VEYHH85VuJwcOg5scaJopbiFQpi3D5GFnngXE+r2avxjFzuHDLzMIh8n+nH3dQEVkrAKXY9pr/GSRP+sNCiX0+nODp7CaCDTR3mY65GYFpCsNdT74+lS4bUSziug3aFjvXZTq21zRLEfYoLBOo6Ro0d4iBU5z/hW1FMSooS3yM1Tzj1fji08E1VhtscJ4OZA19i7nvuIji1wPZzzNULsV6HdCGFN1U2qh/9atiCuJ82B5cwTTv94HXQc8TjzK657p9bEozEIiQ62kfiNzWsw/L7RxHwD09ZQ16w4AF6y8EYnnvGN8snVZe8w6j6KFfHfvpauIHnbgSfwRDCmbWYKExeUH1P54cjlO8wiY90ZwZ9PI4FYi33FUQbQf4dk=
  app: obscure-spire-41744
